name: Cypress Tests

on:
  push:
    branches: [test, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      BASE_API: ${{ secrets.BASE_API }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run